project:
  type: book

book:
  title: "Use of AI Coding Assistants in R Package Development"
  subtitle: "Creating R packages with assistance from Github Copilot or ChatGPT"
  author: "Sam Parmar"
  date: "3/13/2023"
  site-url: parmsam.github.io/ai-code-r-pkgs/
  repo-url: https://github.com/parmsam/ai-code-r-pkgs
  chapters:
    - index.qmd
    - intro.qmd
    - overview.qmd
    - functions.qmd
    - testing.qmd
    - vignettes.qmd
    - combining.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt

