project:
  type: book

book:
  title: "Use of AI Coding Assistants in R Package development"
  subtitle: "Creating R packages with assistance from Copilot or ChatGPT"
  author: "Sam Parmar"
  date: "3/13/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - overview.qmd
    - functions.qmd
    - testing.qmd
    - vignettes.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt

