# Introduction

## In this book

Whether you are an experienced R package developer looking to improve your workflow, or a data scientist interested in building packages to share your work with others, this book will provide valuable insights into how AI coding assistants can help you build your packages more efficiently. Specifically, we will go over [ChatGPT](https://openai.com/blog/chatgpt) and [Github Copilot](https://github.com/features/copilot), two of the most popular AI coding assistants currently available. 

[Chapter -@sec-overview] will provide an overview of these tools. We will then dive into individual chapters on how these tools can assist with the development of functions in [chapter -@sec-functions], unit tests in [chapter -@sec-testing], and vignettes in [chapter -@sec-vignettes], providing practical examples and best practices along the way.

## Prerequisites

We assume that the reader has prior experience developing R packages and is familiar with the basics of package development, including the use of [devtools](https://devtools.r-lib.org/), [usethis](https://usethis.r-lib.org/), [roxygen2](https://roxygen2.r-lib.org/), and [testthat](https://testthat.r-lib.org/). Additionally, we assume that the reader has already read [R Packages](https://r-pkgs.org/) by Hadley Wickham and Jenny Bryan, which provides an excellent introduction to R package development. Lastly, we assume that the reader has a good understanding of the R language and its ecosystem. This is important to recognize bugs or ["hallucinations"](https://en.wikipedia.org/wiki/Hallucination_(artificial_intelligence)) generated by ChatGPT.

## Philosophy

This book advocates for the use of AI code assistants to improve your productivity. However, it shouldn't replace good understanding of your code and selected programming language. Developers should be aware of current [common failures](https://arxiv.org/abs/2302.03494) of systems they may be using. Also readers should be cautious about use of tools like [ChatGPT to avoid learning](https://youtu.be/IgxzcOugvEI?t=214).

## Privacy

Ensure that you don't provide AI code assistants such as ChatGPT or Github CoPilot with sensitive code or data. There have already been many cases of [employees pasting sensitive data](https://www.darkreading.com/risk/employees-feeding-sensitive-business-data-chatgpt-raising-security-fears), and some [estimates of how common this is](https://www.cyberhaven.com/blog/4-2-of-workers-have-pasted-company-data-into-chatgpt/). We'd recommend reading the privacy policy for the AI assistant that you'd using and recommend ensuring sensitive data is kept separate. 

## What you won't learn

Here are some topics you won't learn about in this book:

* Developing your first R package
* Creating a large language model like ChatGPT
* Using AI code assistants for analysis with R

## Colophon

This book was created using [Quarto](https://quarto.org/docs/books/). The website is hosted on Github pages and the code is available on [Github](https://github.com/parmsam/ai-code-r-pkgs).

## Ethical considerations

### Risk of Plaigarism

Although there is evidence that AI code assistants can significantly improve productivity ([a](https://arxiv.org/abs/2302.06590),[b](https://github.blog/2022-09-07-research-quantifying-github-copilots-impact-on-developer-productivity-and-happiness/), [c](https://github.blog/2022-07-14-research-how-github-copilot-helps-improve-developer-productivity/)), there have been cases of unintentional plagiarism or copyright violation associated with ChatGPT use that you should also be aware of when using such tools for niche cases:
 
* Such as a puzzle game called [Sumplete](https://www.digitaltrends.com/gaming/sumplete-chatgpt-ai-game-design-ethics/)
* Or possible [class action lawsuits](https://www.theverge.com/2022/11/8/23446821/microsoft-openai-github-copilot-class-action-lawsuit-ai-copyright-violation-training-data)


<!-- * [ChatGPT and Software Testing Education: Promises & Perils](https://arxiv.org/abs/2302.03287) -->
<!-- * [Exploring AI Ethics of ChatGPT: A Diagnostic Analysis](https://arxiv.org/abs/2301.12867) -->

## Disclaimer

Please note that this book was written with assistance from ChatGPT because it's only right that a book on the use of AI assistants was written with [some help from ChatGPT](https://media.giphy.com/media/qAtZM2gvjWhPjmclZE/giphy.gif). 😁